name: Restoran-backend

on:
  push:
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Print debugging information
        run: |
          echo "python version: ${python --version}"
          echo "working director: ${PWD}"
          echo "Content of working directory: $(ls -l)"
          echo "contents of site-packages: $(ls -l venv/lib/python*/site-packages)"
